implemented rowcumsum

diff --git a/scripts/staging/SIMD-double-vectors/systemds b/scripts/staging/SIMD-double-vectors/systemds
--- a/scripts/staging/SIMD-double-vectors/systemds
+++ b/scripts/staging/SIMD-double-vectors/systemds
@@ -20,6 +20,14 @@
 #
 #-------------------------------------------------------------
 
+##############################################################
+# This script is part of the SystemDS binary release. It is
+# meant to work out of the box when unzipping the
+# systemds-<version>.zip (or tbz) file.
+#
+# Make configuration changes here:
+##############################################################
+
 #  If not set by env,  set to 1 to run spark-submit instead of local java
 #  This should be used to run with spark-submit instead of java
 if [[ -z "$SYSDS_DISTRIBUTED" ]]; then
@@ -48,12 +56,15 @@ print_out()
 }
 
 if [[ -z $SYSTEMDS_ROOT ]] ; then
-  SYSTEMDS_ROOT=$(pwd)
+  SYSTEMDS_ROOT=.
   print_out "SYSTEMDS_ROOT not set defaulting to current dir $(pwd)"
+else
+  # construct a relative path
+  SYSTEMDS_ROOT=$(realpath --relative-to=. ${SYSTEMDS_ROOT})
 fi;
 
 # when using find, look in the directories in this order
-DIR_SEARCH_ORDER="$SYSTEMDS_ROOT/target . $SYSTEMDS_ROOT $SYSTEMDS_ROOT/conf  $SYSTEMDS_ROOT/lib $SYSTEMDS_ROOT/src"
+DIR_SEARCH_ORDER=". $SYSTEMDS_ROOT $SYSTEMDS_ROOT/conf  $SYSTEMDS_ROOT/lib $SYSTEMDS_ROOT/src $SYSTEMDS_ROOT/target"
 ordered_find() {
   result=""
   for dir in $(echo "$DIR_SEARCH_ORDER" | tr ' ' '\n') ; do
@@ -84,19 +95,21 @@ fi
 # check if log4j config file exists, otherwise unset
 # to run with a non fatal complaint by SystemDS
 if [ -z "$LOG4JPROP" ] ; then
-  # before wild card search look obvious places.
-  if [ -f "$SYSTEMDS_ROOT/conf/log4j.properties" ]; then 
-    LOG4JPROP="$SYSTEMDS_ROOT/conf/log4j.properties"
-  elif [ -f "$SYSTEMDS_ROOT/log4j.properties" ]; then 
-    LOG4JPROP="$SYSTEMDS_ROOT/log4j.properties"
-  else # wildcard search
-    LOG4JPROP=$(ordered_find "log4j*properties")
-  fi
-fi
+  LOG4JPROP=$(ordered_find "log4j*properties")
 
-# If the LOG4J variable is declared or found.
-if [ -f "${LOG4JPROP}" ]; then
-  LOG4JPROPFULL="-Dlog4j.configuration=file:$LOG4JPROP"
+  if [ -z "${LOG4JPROP}" ]; then
+    LOG4JPROP=""
+  else
+    LOG4JPROP="-Dlog4j.configuration=file:$LOG4JPROP"
+  fi
+else
+  # L4J was set by env var. Unset if that setting is wrong
+  LOG4JPROP2=$(find "$LOG4JPROP")
+  if [ -z "${LOG4JPROP2}" ]; then
+    LOG4JPROP=""
+  else
+    LOG4JPROP="-Dlog4j.configuration=file:$LOG4JPROP2"
+  fi
 fi
 
 if [ -n "${SYSTEMDS_DISTRIBUTED_OPTS}" ]; then
@@ -113,12 +126,22 @@ else
       --files $LOG4JPROP \
       --conf spark.network.timeout=512s \
       --num-executors 4 \
-      --executor-memory 64g \
+      --executor-memory 64 \
       --executor-cores 16 "
 fi
 
 
+##############################################################
+# No need to touch the content below. These commands launch
+# SystemDS based on the settings above.
+##############################################################
+
+
+#-------------------------------------------------------------
+# some helper functions
+
 # error help print
+PRINT_SYSDS_HELP=0
 function printUsage {
 cat << EOF
 
@@ -144,10 +167,6 @@ Worker Usage: $0 [-r] WORKER [SystemDS.jar] <portnumber> [arguments] [-help]
 
     port         : The port to open for the federated worker.
 
-Federated Monitoring Usage: $0 [-r] FEDMONITORING [SystemDS.jar] <portnumber> [arguments] [-help]
-
-    port         : The port to open for the federated monitoring tool.
-
 Set custom launch configuration by setting/editing SYSTEMDS_STANDALONE_OPTS
 and/or SYSTEMDS_DISTRIBUTED_OPTS.
 
@@ -156,6 +175,9 @@ local java Set SYSDS_QUIET=1 to omit extra information printed by this run
 script.
 
 EOF
+if [ ${PRINT_SYSDS_HELP} -eq 0 ]; then
+  exit 0
+fi
 }
 
 # print an error if no argument is supplied.
@@ -163,18 +185,16 @@ if [ -z "$1" ] ; then
     echo "Wrong Usage. Add -help for additional parameters.";
     echo ""
     printUsage;
-    exit -1
 fi
 
 #This loop handles the parameters to the run-script, not the ones passed to SystemDS.
 #To not confuse getopts with SystemDS parameters, only the first two params are considered
 #here. If more run-script params are needed, adjust the next line accordingly
-PRINT_SYSDS_HELP=0
 while getopts ":hr:f:" options "$1$2"; do
   case $options in
     h ) echo "Help requested. Will exit after extended usage message!"
-        printUsage
         PRINT_SYSDS_HELP=1
+        printUsage
         break
         ;;
     \? ) echo "Unknown parameter -$OPTARG"
@@ -267,33 +287,17 @@ if [ -z "$FEDMONITORING" ] ; then
   FEDMONITORING=0
 fi
 
-# find a SystemDS jar file to run
-if [ -z ${SYSTEMDS_JAR_FILE+x} ]; then # If it is not found yet.
-  if [ ! -z ${SYSTEMDS_ROOT+x} ]; then # Check currently set SYSETMDS_ROOT
-    # Current SYSTEMDS_ROOT is set and is a directory.
-    if [ -d "$SYSTEMDS_ROOT/target" ] && [ -d "$SYSTEMDS_ROOT/.git" ]; then 
-      # Current path is most likely a build directory of systemds
-      SYSTEMDS_JAR_FILE=$(find "$SYSTEMDS_ROOT/target" -maxdepth 1 -iname ""systemds-?.?.?-SNAPSHOT.jar"" -print -quit)
-    elif [ -d "$SYSTEMDS_ROOT" ] && [ -d "$SYSTEMDS_ROOT/lib" ]; then
-      # Most likely a release directory.
-      SYSTEMDS_JAR_FILE=$(find "$SYSTEMDS_ROOT" -maxdepth 1 -iname ""systemds-?.?.?-SNAPSHOT.jar"" -print -quit)
-    fi
-  fi 
-fi 
-
-# If no jar file is found, start searching --- expected + 70 ms execution time
-if [ -z ${SYSTEMDS_JAR_FILE+x} ]; then 
+# find me a SystemDS jar file to run
+if [ -z "$SYSTEMDS_JAR_FILE" ];then
   SYSTEMDS_JAR_FILE=$(ordered_find "systemds.jar")
-  if [ -z ${SYSTEMDS_JAR_FILE+x} ]; then
+  if [ -z "$SYSTEMDS_JAR_FILE" ];then
     SYSTEMDS_JAR_FILE=$(ordered_find "systemds-?.?.?.jar")
-    if [ -z ${SYSTEMDS_JAR_FILE+x} ]; then
+    if [ -z "$SYSTEMDS_JAR_FILE" ];then
       SYSTEMDS_JAR_FILE=$(ordered_find "systemds-?.?.?-SNAPSHOT.jar")
-      if [ -z ${SYSTEMDS_JAR_FILE+x} ]; then
-        echo "wARNING: Unable to find SystemDS jar file to launch"
-        exit -1
-      fi  
     fi
   fi
+else
+  print_out "Using user supplied systemds jar file $SYSTEMDS_JAR_FILE"
 fi
 
 if [[ "$*" == *-config* ]]; then
@@ -329,21 +333,11 @@ if [[ "$*" == *-config* ]]; then
     CONFIG_FILE=""
   fi
 elif [ -z "$CONFIG_FILE" ] ; then
-
-  # default search for config file 
-  if [ -f "$SYSTEMDS_ROOT/conf/SystemDS-config-defaults.xml" ]; then 
-    CONFIG_FILE="$SYSTEMDS_ROOT/conf/SystemDS-config-defaults.xml"
-  elif [ -f "$SYSTEMDS_ROOT/SystemDS-config-defaults.xml" ]; then 
-    CONFIG_FILE="$SYSTEMDS_ROOT/conf/SystemDS-config-defaults.xml"
-  else # wildcard search
-    # same as above: set config file param if the file exists
-    CONFIG_FILE=$(ordered_find "SystemDS-config-defaults.xml")
-  fi
-
-  if [ -z "$CONFIG_FILE" ]; then # Second search if still not found.
+  # same as above: set config file param if the file exists
+  CONFIG_FILE=$(ordered_find "SystemDS-config-defaults.xml")
+  if [ -z "$CONFIG_FILE" ]; then
     CONFIG_FILE=$(ordered_find "SystemDS-config.xml")
   fi
-
   if [ -z "$CONFIG_FILE" ]; then
     CONFIG_FILE=""
   else
@@ -369,77 +363,115 @@ for i in "${myArray[@]}"; do
   (( INDEX=INDEX+1 ))
 done
 
-# find absolute path to hadoop home in SYSTEMDS_ROOT
-if [ -z "$HADOOP_HOME" ]; then
-  HADOOP_HOME="$(find "$SYSTEMDS_ROOT" -iname hadoop | tail -n 1 )"
+if [ $SYSDS_DISTRIBUTED -ne 0 ] && [[ $SYSDS_EXEC_MODE == "singlenode" ]]; then
+  echo "Error: Can not run on Spark with execution mode singlenode"
+  exit 1
 fi
 
+# find absolute path to hadoop home in SYSTEMDS_ROOT
+if [ -z "$HADOOP_HOME" ]; then
+  HADOOP_HOME=$(realpath "$(find "$SYSTEMDS_ROOT" -iname hadoop | tail -n 1 )")
+  export HADOOP_HOME
+fi
+# add hadoop home to path and lib path for loading hadoop jni
+HADOOP_REL=$(realpath --relative-to=. "$HADOOP_HOME")
+
+# default directory separator unix style
+DIR_SEP=/
 # detect operating system to set correct path separator
 if [ "$OSTYPE" == "win32" ] ||  [ "$OSTYPE" == "msys" ] ||  [ "$OSTYPE" == "cygwin" ]; then
   PATH_SEP=\;
   DIR_SEP=\\
+  HADOOP_REL="${HADOOP_REL////\\}"
 else
-  # default directory separator unix style
-  DIR_SEP=/
   PATH_SEP=:
 fi
 
+# make the jar path relative to skip issues with Windows paths
+JARNAME=$(basename "$SYSTEMDS_JAR_FILE")
+
+# relative path to jar file
+SYSTEMDS_JAR_FILE=$(realpath --relative-to=. "$(dirname "$SYSTEMDS_JAR_FILE")")${DIR_SEP}${JARNAME}
 
 NATIVE_LIBS="$SYSTEMDS_ROOT${DIR_SEP}target${DIR_SEP}classes${DIR_SEP}lib"
-PATH=${HADOOP_HOME}${DIR_SEP}bin${PATH_SEP}${PATH}${PATH_SEP}$NATIVE_LIBS
-LD_LIBRARY_PATH=${HADOOP_HOME}${DIR_SEP}bin${PATH_SEP}${LD_LIBRARY_PATH}
+export PATH=${HADOOP_REL}${DIR_SEP}bin${PATH_SEP}${PATH}${PATH_SEP}$NATIVE_LIBS
+export LD_LIBRARY_PATH=${HADOOP_REL}${DIR_SEP}bin${PATH_SEP}${LD_LIBRARY_PATH}
 
+# set java class path
+CLASSPATH="${SYSTEMDS_JAR_FILE}${PATH_SEP} \
+          ${SYSTEMDS_ROOT}${DIR_SEP}lib${DIR_SEP}*${PATH_SEP} \
+          ${SYSTEMDS_ROOT}${DIR_SEP}target${DIR_SEP}lib${DIR_SEP}*"
+# trim whitespace (introduced by the line breaks above)
+CLASSPATH=$(echo "${CLASSPATH}" | tr -d '[:space:]')
 
 if [ $PRINT_SYSDS_HELP == 1 ]; then
   echo "----------------------------------------------------------------------"
   echo "Further help on SystemDS arguments:"
-  java -jar $SYSTEMDS_JAR_FILE org.apache.sysds.api.DMLScript -help
+  java -cp "$CLASSPATH" org.apache.sysds.api.DMLScript -help
   exit 1
 fi
 
-if [ $SYSDS_QUIET == 0 ]; then
-  print_out "###############################################################################"
-  print_out "#  SYSTEMDS_ROOT= $SYSTEMDS_ROOT"
-  print_out "#  SYSTEMDS_JAR_FILE= $SYSTEMDS_JAR_FILE"
-  print_out "#  SYSDS_EXEC_MODE= $SYSDS_EXEC_MODE"
-  print_out "#  CONFIG_FILE= $CONFIG_FILE"
-  print_out "#  LOG4JPROP= $LOG4JPROPFULL"
-  print_out "#  HADOOP_HOME= $HADOOP_HOME"
-  print_out "#"
-fi
+print_out "###############################################################################"
+print_out "#  SYSTEMDS_ROOT= $SYSTEMDS_ROOT"
+print_out "#  SYSTEMDS_JAR_FILE= $SYSTEMDS_JAR_FILE"
+print_out "#  SYSDS_EXEC_MODE= $SYSDS_EXEC_MODE"
+print_out "#  CONFIG_FILE= $CONFIG_FILE"
+print_out "#  LOG4JPROP= $LOG4JPROP"
+print_out "#  CLASSPATH= $CLASSPATH"
+print_out "#  HADOOP_HOME= $HADOOP_HOME"
 
-# Build the command to run
+#build the command to run
 if [ $WORKER == 1 ]; then
+  print_out "#"
   print_out "#  starting Federated worker on port $PORT"
+  print_out "###############################################################################"
   CMD=" \
   java $SYSTEMDS_STANDALONE_OPTS \
-  $LOG4JPROPFULL \
-  -jar $SYSTEMDS_JAR_FILE \
+  -cp $CLASSPATH \
+  $LOG4JPROP \
+  org.apache.sysds.api.DMLScript \
   -w $PORT \
   $CONFIG_FILE \
   $*"
+  print_out "Executing command: $CMD"
+  print_out  ""
+
 elif [ "$FEDMONITORING" == 1 ]; then
+  print_out "#"
   print_out "#  starting Federated backend monitoring on port $PORT"
+  print_out "###############################################################################"
   CMD=" \
   java $SYSTEMDS_STANDALONE_OPTS \
-  $LOG4JPROPFULL \
-  -jar $SYSTEMDS_JAR_FILE \
+  -cp $CLASSPATH \
+  $LOG4JPROP \
+  org.apache.sysds.api.DMLScript \
   -fedMonitoring $PORT \
   $CONFIG_FILE \
   $*"
-elif [ $SYSDS_DISTRIBUTED == 0 ]; then
-  print_out "#  Running script $SCRIPT_FILE locally with opts: $*"
+  print_out "Executing command: $CMD"
+  print_out  ""
 
+elif [ $SYSDS_DISTRIBUTED == 0 ]; then
+  print_out "#"
+  print_out "#  Running script $SCRIPT_FILE locally with opts: $*"
+  print_out "###############################################################################"
   CMD=" \
   java $SYSTEMDS_STANDALONE_OPTS \
-  $LOG4JPROPFULL \
-  -jar $SYSTEMDS_JAR_FILE \
+  -cp $CLASSPATH \
+  $LOG4JPROP \
+  --add-modules=jdk.incubator.vector \
+  org.apache.sysds.api.DMLScript \
   -f $SCRIPT_FILE \
   -exec $SYSDS_EXEC_MODE \
   $CONFIG_FILE \
   $*"
+  print_out "Executing command:  $CMD"
+  print_out ""
 else
+  print_out "#"
   print_out "#  Running script $SCRIPT_FILE distributed with opts: $*"
+  print_out "###############################################################################"
+  export SPARK_MAJOR_VERSION=2
   CMD=" \
   spark-submit $SYSTEMDS_DISTRIBUTED_OPTS \
   $SYSTEMDS_JAR_FILE \
@@ -447,11 +479,8 @@ else
   -exec $SYSDS_EXEC_MODE \
   $CONFIG_FILE \
   $*"
-fi
-
-if [ $SYSDS_QUIET == 0 ]; then
-  print_out "#  Executing command: $CMD"
-  print_out "###############################################################################"
+  print_out "Executing command: $CMD"
+  print_out  ""
 fi
 
 # run
